### ISSUE TITLE
This looks great! BOM?

### ISSUE THREAD

**Issue by samuk** [kallaspriit/rosbot#1]
Hi nice work this looks like a good machine. Is there a BOM available anywhere?

**Comment by grafoteka** [comment]
Hi @kallaspriit, thank you for sharing the project, it looks great!

I'm with @samuk, is available any BOM of the project? From your video I have identify these components:

- RPlidar S1 ([https://www.slamtec.com/en/Lidar/S1](https://www.slamtec.com/en/Lidar/S1))
- Brushless motor X8308S ([https://es.aliexpress.com/i/32837933318.html](https://es.aliexpress.com/i/32837933318.html)) 
- IMU BNO-055 ([https://tienda.bricogeek.com/medicion-inercial-imu/802-sensor-inercial-absoluto-9-dof-bno055.html](https://tienda.bricogeek.com/medicion-inercial-imu/802-sensor-inercial-absoluto-9-dof-bno055.html))
- RPI 4B
- Adafruit Feather nRF52840 Sense ([https://learn.adafruit.com/adafruit-feather-sense](https://learn.adafruit.com/adafruit-feather-sense))
- ODrive 3.6 Brushless controller [https://odriverobotics.com/shop/odrive-v36](https://odriverobotics.com/shop/odrive-v36)
- TLE5012B Magnetic Motors Encoders - I could not found with module it is.
- Belt Drive HTD 4.5:1 Gear Ratio
- 32V Battery from Segway Ninebot ES4

**Comment by kallaspriit** [comment]
Hey, you've got it right. I've updated the README with link to my own complete BOM. It was not really made for easy replication but rather for myself but maybe it helps :)
