### ISSUE TITLE
rplidar data frame

### ISSUE THREAD

**Issue by HusamZain** [kallaspriit/rosbot#4]
Great work, and thank you for sharing !
I'm building the same project and using almost the same hardware you have , but I'm facing a problem with the Laserscan data that published from the rplidar package that you used ,  it's rotates with the robot when I rotate the robot, so I was wondering if you countered the same issue when you worked with rplidar? 
as you can see in the pic, the laserscan data rotates when I rotate the robot, not sure is it beacouse the TF, but I have a similar urdf file as yours(odom>>base_link and base_link>>lidar_link)

**Comment by kallaspriit** [comment]
Haven't had problems with the library, check your transforms :)
